name: Flutter Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Analyze the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: Install packages
        run: flutter pub get
      - name: Generate localizations
        run:  flutter gen-l10n
      - name: Generate configs
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Linter
        run: flutter analyze
      - name: Test the code
        run: flutter test
