name: Flutter Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Analyze the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: Install packages
        run: flutter pub get
      - name: Build Linux AppImage
        run: flutter build linux --release --verbose 
      - name: Package as AppImage
        run: |
          wget -nv https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage ./build/linux/release/bundle/flutter_project-1.0.0-x86_64.AppDir
