name: Build AppImage and DMG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0
      - run: sudo snap install flutter --classic
      - run: flutter doctor
      - run: sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      - run: flutter clean
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      
      - name: Package as AppImage
        run: |
          wget -nv https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage ./build/linux/release/bundle/flutter_project-1.0.0-x86_64.AppDir
