name: Build AppImage and DMG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Set up Flutter
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
     
      - run: |
          flutter clean
          flutter pub upgrade
          flutter pub get
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter build linux
      
      - name: Package as AppImage
        run: |
          wget -nv https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage ./build/linux/release/bundle/flutter_project-1.0.0-x86_64.AppDir
