name: Builds
on:
  release:
    types:
      - published
  push:
    branches:
      - main
  pull_request:

# Declare default permissions as read only.
permissions: read-all

jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: |
           sudo apt-get update -y
           sudo apt-get install -y ninja-build libgtk-3-dev
        - run: flutter config --enable-linux-desktop
        - run: flutter build linux --release
        - run: |
             wget -nv https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
             chmod +x appimagetool-x86_64.AppImage
             ./appimagetool-x86_64.AppImage ./build/linux/x64/release/bundle/my_github_app.AppDir
        - uses: actions/upload-artifact@v2
          with:
            name: Build
            path: build