name: Build

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  flutter:
    strategy:
      # Some tests are falky. disable fail fast so the parallel jobs are not
      # immediately cancelled when a test fails due to flake.
      fail-fast: false
      matrix:
        channel:
          - stable
          - beta
          - main
        os:
          - macos-latest
          - ubuntu-latest
        package-path:
          - '.'
          - 'example'

    defaults:
      run:
        working-directory: ${{ matrix.package-path }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 2

      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: ${{ matrix.channel }}

      - name: Flutter doctor
        run: flutter doctor --verbose --no-version-check

      - name: Install dependencies
        run: flutter pub get

      - name: Check format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: |
          if test -d "test"; then
            flutter test --coverage
          fi
